import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '../globals.css'
import { Footer, Header } from '@/components'
import { Content } from '../Content'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
   <div className='w-screen h-screen flex flex-col overflow-hidden'>
    <Header/>
    <Content>
        {children}
    </Content>
    <Footer/>
   </div>
  )
}
